export const KeyForm = {
    CanNhanToChuViPham: 1,
    CapCoThamQuyenXuPhat: 2,
    CaNhanQuyetDinhXuPhat: 3,
    NgaySinh: 4,
    QuocTich: 5,
    NguyenQuan: 6,
    HoKhauThuongTru: 7,
    DiaChiHienTai: 8,
    CMND: 9,
    LinhVuc: 10,
    HanhViViPham: 11,
    CanCuPhapLyXuPhat: 12,
    TongMucTienPhat: 13,
    HinhThucXuPhatBoSung: 14,
    BienPhanNganChanVaDamBao: 15,
    NgayQDXuPhat: 16,
    CoQuanThiHanh: 17,
    CaNhanCoTrachNhiemToChucThiHanh: 18,
    TrangThaiThiHanh: 19,
    NgayThucThi: 20,
    SoNgayQuaHan: 21,
    NoiCap: 22,
    NgayCap: 23,
    SoDienThoai: 24,
    TenCongTy: 25,
    MaSoCongTy: 26,
}