const ObjectDataYTe = {
    cosoId: "cosoId",
    numDaLapHS: "numDaLapHS",
    macBenhNams: "macBenhNams",
    numTreEm: "numTreEm",
    benhTruyenNhiems: "benhTruyenNhiems",
    nuDaiThaoDuongXa: "nuDaiThaoDuongXa",
    cosoTen: "cosoTen",
    namBenhManTinh: "namBenhManTinh",
    nuTangHuyetApXa: "nuTangHuyetApXa",
    namDaiThaoDuong: "namDaiThaoDuong",
    nuDaiThaoDuong: "nuDaiThaoDuong",
    ttCapDuoi: "ttCapDuoi",
    nuTangHuyetAp: "nuTangHuyetAp",
    ngayKhamChuaBenh: "ngayKhamChuaBenh",
    namBenhManTinhXa: "namBenhManTinhXa",
    namDaiThaoDuongXa: "namDaiThaoDuongXa",
    namTangHuyetApXa: "namTangHuyetApXa",
    numDaKhoiTaoHS: "numDaKhoiTaoHS",
    numNhanKhau: "numNhanKhau",
    numNguoiCaoTuoi: "numNguoiCaoTuoi",
    nuBenhManTinhXa: "nuBenhManTinhXa",
    numHoKhau: "numHoKhau",
    ctCssk: "ctCssk",
    numPhuNu: "numPhuNu",
    soHoSoTiemChung: "soHoSoTiemChung",
    nuBenhManTinh: "nuBenhManTinh",
    macBenhNus: "macBenhNus",
    soHosoKhamChuaBenh: "soHosoKhamChuaBenh",
    namTangHuyetAp: "namTangHuyetAp",
    keynew: "keynew",
}
export default ObjectDataYTe