import { ImagesSVL } from "../images";

export const dataTinTD = [
    {
        id: 1,
        title: 'Nhân viên / Chuyên viên ngành hàng hệ thống siêu thị VLXD và nội thất Hoa Sen',
        thumbnailUrl: ImagesSVL.imgHoaSen,
        company: 'Công Ty Cổ Phần Tập Đoàn Hoa Sen',
        address: '142TL8, Bình Thạnh, Hồng Ngự',
        salary: '8 - 15 triệu',
        typeWork: 'Toàn thời gian',
        thoihan: '30/11/2021',
        view: '123',
        typeCompany: 'Loại hình: Doanh nghiệp, công ty \n \n Số lao động cần tuyển: 10 nam/ nữ \n \n Ngành nghề: Chuyên viên \n \n Chức danh: Nhân viên/ công nhân \n \n Loại hình lao động: Người lao động',
        Mota: 'Để đạt được những thành tựu trên và phát triển hơn nữa trong thời gian đến thì đội ngũ nhân sự là một trong các yếu tố quan trọng. Do đó, công tác tuyển dụng, đào tạo và phát triển nguồn nhân lực trẻ luôn được Tập đoàn chú trọng nhằm xây dựng một đội ngũ nhân sự dự nguồn tài năng, nhiệt huyết, sáng tạo. Trên cơ sở đó, chúng tôi đang tìm kiếm các ứng viên kinh doanh với quy mô rộng khắp cả nước cùng khung chương trình đào tạo, phát triển và lộ trình thăng tiến được thiết kế khoa học, các chế độ phúc lợi hấp dẫn nhằm mục đích tuyển chọn những nhân sự tài năng đang khát khao, mong muốn dấn thân hết mình để phát triển sự nghiệp tại Tập đoàn Hoa Sen.\n \n Ngành hàng sản phẩm thương mại: Gạch, Thép, Sơn, Điện dân dụng, Thiết bị vệ sinh, Ngói, Công cụ dụng cụ, Bồn nước,… \n \n- Thực hiện công tác phân tích, nghiên cứu khảo sát các nhà cung cấp, sản phẩm mới để kinh doanh ở Hệ thống phân phối, đẩy mạnh công tác bán hàng thương mại ở Chi nhánh/Cửa hàng khu vực được giao.\n \n - Tìm kiếm, liên hệ với các nhà cung cấp, đối tác tiềm năng, đàm phán thương lượng thỏa thuận kinh doanh thương mại và ký kết hợp đồng.\n \n - Thu thập thông tin, tổng hợp và báo cáo cho Trưởng đơn vị về các vấn đề có liên quan đến kinh doanh thương mại như: sản lượng, hàng tồn kho, cách cửa hàng triển khai kinh doanh.\n \n - Hỗ trợ Chi nhánh/Cửa hàng các công tác liên quan đến bán hàng, kiến thức sản phẩm,... Nơi làm việc:\n \n - Các Tỉnh/Thành trên toàn quốc có Hệ thống Siêu thị VLXD & Nội thất Hoa Sen Home.\n \n * Lưu ý: Ứng viên có thể chọn ngành hàng kinh doanh và nơi làm việc phù hợp để ứng tuyển.',
        yeucau: '- Nam, tốt nghiệp Trung cấp trở lên tất cả các chuyên ngành liên quan.\n \n - Ưu tiên ứng viên có kinh nghiệm kinh doanh tối thiểu 1 năm các lĩnh vực: Gạch, Thép, Sơn, Điện dân dụng, Thiết bị vệ sinh, Ngói, Công cụ dụng cụ, Bồn nước,\n \n- Giao tiếp tốt, yêu thích công việc kinh doanh, không ngại đi công tác trong tỉnh.\n \n - Ưu tiên ứng viên làm việc và công tác tại Tỉnh.\n \n - Trung thực, năng động, tinh thần tự giác cao, gắn bó lâu dài.\n \n- Kỹ năng làm việc độc lập, làm việc nhóm\n \n - Kỹ năng vi tính văn phòng tốt: Word, Excel.',
        isSave: true,
        isApply: false,
        appliedDate: '10:38 25/12/2021',
        status: 0,
        dateInterview: '08:30 15/1/2022',
        dataUser: {
            name: 'Mr Nguyễn Minh Thông',
            SDT: '0988 050 588',
            address: 'Số 142TL8, Bình Thạnh, Hồng Ngự, Đồng Tháp',
            submitt: false
        }
    },
    {
        id: 2,
        title: 'Nhân viên quản lý kho, khuc vực củ chi. Từ tháng 1 - tháng 3 hỗ trợ xét nghiệm tại công ty',
        thumbnailUrl: ImagesSVL.imgNinja,
        company: 'Công Ty Cổ Phần Giao Hàng Ninja',
        address: 'Số 13 QL30, An Bình, Hồng Ngự',
        salary: 'Thoả thuận',
        typeWork: 'Toàn thời gian',
        thoihan: '30/11/2021',
        view: '123',
        typeCompany: 'Loại hình: Doanh nghiệp, công ty \n \n Số lao động cần tuyển: 10 nam/ nữ \n \n Ngành nghề: Chuyên viên \n \n Chức danh: Nhân viên/ công nhân \n \n Loại hình lao động: Người lao động',
        Mota: `• Kiểm soát số liệu và các báo cáo liên quan đến hoạt động của Kho, kiểm tra tồn kho, số liệu kiểm đếm, tình trạng vận chuyển; vật tư ,…\nCarry on department reports and indexes: warehouse customer service, bundling levels, inventory audits and cycle count results, shipping discrepancies, inventory accuracy for unpacks, production supplies\n \n• Đảm bảo quy trình xuất nhập của cut part và vật tư\nAssure the constant flow of cut parts, supplies and the export process\n \n• Nghiên cứu và phân tích các phương pháp cải tiến quy trình, thủ tục nhằm tăng`,
        yeucau: `• Tốt nghiệp Đại học ngành trở lên ở các lĩnh vực liên quan\nUniversity Degree or above in related fields\n \n• 3- 5 năm kinh nghiệm ở vị trí tương tự\n3-5 years of experience on similar positions\n \n• Kinh nghiệm liên quan đến Kho vận/ kê hoạch/ mua hàng/ kiểm soát vật tư\nExperience in warehouse management/planning/ purchasing/ materials\n \n• Thành thạo tiếng Anh\nFluency in English\n \n• Kỹ năng xử lý các tình huống khẩn cấp\nHigh sense of urgency\n \n• Khả năng lãnh đạo\nLeadership\n \n• Khả năng giải quyết vấn đề\nProblem Solving\n \n• Kiến thức cải tiến quy trình\nProcess Improvement\n \n• Kiến thức về Thủ tục Hải quan\nDeep knowledge about customs procedures`,
        isSave: false,
        isApply: false,
        appliedDate: '10:38 25/12/2021',
        status: 0,
        dateInterview: '08:30 15/1/2022',
        dataUser: {
            name: 'Mrs Nguyễn Kim Hồng',
            SDT: '0988 333 666',
            address: 'Số 13 QL30, An Bình, Hồng Ngự, Đồng Tháp',
            submitt: false
        }
    },
    {
        id: 3,
        title: 'Chuyên Viên Đặt Hẹn Khách Hàng Qua Điện Thoại - Telemarketing',
        thumbnailUrl: ImagesSVL.icDemoBosch,
        company: 'Công Ty Cổ Phần Bosch',
        address: '33 Đường Tân Hội, An Thạnh, Hồng Ngự',
        salary: '300$ - 1200$',
        typeWork: 'Bán thời gian',
        thoihan: '30/11/2021',
        view: '123',
        typeCompany: 'Loại hình: Doanh nghiệp, công ty \n \n Số lao động cần tuyển: 10 nam/ nữ \n \n Ngành nghề: Chuyên viên \n \n Chức danh: Nhân viên/ công nhân \n \n Loại hình lao động: Người lao động',
        Mota: `- Analyzing and translating business needs into long-term solution data models.\n- Working with Customers and development team to design and develop conceptual, logical and physical data models.\n- Evaluating existing data systems.\n- Evaluating implemented data systems for variances, discrepancies, and efficiency.\n- Developing best practices for data coding to ensure consistency within the system.\n- Reviewing modifications of existing systems for cross-compatibility.\n- Updating and optimizing local and metadata models.\n- Troubleshooting and optimizing data systems.\n- Documents data architecture and data modeling solutions`,
        yeucau: `- Bachelor degree in IT/ Computer Science or relevant background\n - Strong experience in Data Warehouse development, incl. logical & physical database design\n - Strong experience in database modeling methods (e.g. Relational, Dimensional, Data Vault 2.0 modeling)\n - Experience in database modeling tools, e.g. Oracle Data Modeler, Power Designer…\n - Strong experience in SQL, PL/SQL\n - Good at English communication skills`,
        isSave: false,
        isApply: false,
        appliedDate: '10:38 25/12/2021',
        status: 1,
        dateInterview: '08:30 15/1/2022',
        dataUser: {
            name: 'Trần Minh Đức',
            SDT: '0909 050 588',
            address: '33 Đường Tân Hội, An Thạnh, Hồng Ngự, Đồng Tháp',
            submitt: false
        }
    },
    {
        id: 4,
        title: '[Hồng Ngự] - Corporate Credit Evaluation Deputy Manager/ Supervisor - Thẩm Định Khách Hàng Doanh Nghiệp',
        thumbnailUrl: ImagesSVL.icDemoTPBank,
        company: 'Ngân hàng Thương mại TP Bank',
        address: '345 Đường Tân Hội, Bình Thạnh, Hồng Ngự',
        salary: '6 - 17 triệu',
        typeWork: 'Bán thời gian',
        thoihan: '30/11/2021',
        view: '123',
        typeCompany: 'Loại hình: Doanh nghiệp, công ty \n \n Số lao động cần tuyển: 10 nam/ nữ \n \n Ngành nghề: Chuyên viên \n \n Chức danh: Nhân viên/ công nhân \n \n Loại hình lao động: Người lao động',
        Mota: `• Kiểm soát số liệu và các báo cáo liên quan đến hoạt động của Kho, kiểm tra tồn kho, số liệu kiểm đếm, tình trạng vận chuyển; vật tư ,…\nCarry on department reports and indexes: warehouse customer service, bundling levels, inventory audits and cycle count results, shipping discrepancies, inventory accuracy for unpacks, production supplies\n \n• Đảm bảo quy trình xuất nhập của cut part và vật tư\nAssure the constant flow of cut parts, supplies and the export process\n \n• Nghiên cứu và phân tích các phương pháp cải tiến quy trình, thủ tục nhằm tăng`,
        yeucau: `• Tốt nghiệp Đại học ngành trở lên ở các lĩnh vực liên quan\nUniversity Degree or above in related fields\n \n• 3- 5 năm kinh nghiệm ở vị trí tương tự\n3-5 years of experience on similar positions\n \n• Kinh nghiệm liên quan đến Kho vận/ kê hoạch/ mua hàng/ kiểm soát vật tư\nExperience in warehouse management/planning/ purchasing/ materials\n \n• Thành thạo tiếng Anh\nFluency in English\n \n• Kỹ năng xử lý các tình huống khẩn cấp\nHigh sense of urgency\n \n• Khả năng lãnh đạo\nLeadership\n \n• Khả năng giải quyết vấn đề\nProblem Solving\n \n• Kiến thức cải tiến quy trình\nProcess Improvement\n \n• Kiến thức về Thủ tục Hải quan\nDeep knowledge about customs procedures`,
        isSave: false,
        isApply: false,
        appliedDate: '10:38 25/12/2021',
        status: 2,
        dateInterview: '08:30 15/1/2022',
        dataUser: {
            name: 'Mai Minh Đức',
            SDT: '0909 050 658',
            address: '345 Đường Tân Hội, Bình Thạnh, Hồng Ngự, Đồng Tháp',
            submitt: false
        }
    },
    {
        id: 5,
        title: 'Trade Marketing Coordinator',
        thumbnailUrl: ImagesSVL.icDemoJotun,
        company: 'Công ty Cổ Phần Sơn Jotun',
        address: '27 Trần Hưng Đạo, An Thạnh, Hồng Ngự',
        salary: '9 - 14 triệu',
        typeWork: 'Toàn thời gian',
        thoihan: '30/11/2021',
        view: '43',
        typeCompany: 'Loại hình: Doanh nghiệp, công ty \n \n Số lao động cần tuyển: 10 nam/ nữ \n \n Ngành nghề: Chuyên viên \n \n Chức danh: Nhân viên/ công nhân \n \n Loại hình lao động: Người lao động',
        Mota: `Hỗ trợ phần mềm\n\n- Xử lý sự cố, khắc phục lỗi phần mềm khi có yêu cầu.\n - Xây dựng thêm chức năng, report cho phần mềm dựa trên tài liệu phân tích nghiệp vụ.\n\n Xây dựng và phát triển phần mềm cho hệ thống.\n - Kinh nghiệm đọc và xử lí, tổ chức code tốt, nắm bắt yêu cầu nghiệp vụ nhanh.\n - Tham gia xây dựng lại phần mềm lõi, xây dựng report, vận hành phần mềm mới trên nền công nghệ mới.`,
        yeucau: `Trình độ: Đại học, chuyên ngành Công nghệ thông tin, công nghệ phần mềm\n\nĐộ tuổi: 24-28\n Kinh nghiệm: ít nhất 2 năm\n Thái độ: tích cực, ham học hỏi, chịu được áp lực\n Ngoại ngữ: Trung cấp (# level B)\n\nSkills and Qualifications/ Kỹ năng Nghiệp vụ:\n - Có khả năng thuyết trình, giao tiếp tốt, có khả năng làm việc nhóm`,
        isSave: false,
        isApply: false,
        appliedDate: '10:38 25/12/2021',
        status: 0,
        dateInterview: '08:30 15/1/2022',
        dataUser: {
            name: 'Lê Văn Cường',
            SDT: '0977 054 079',
            address: '27 Trần Hưng Đạo, An Thạnh, Hồng Ngự, Đồng Tháp',
            submitt: false
        }
    },
    {
        id: 6,
        title: 'Customer Marketing Manager',
        thumbnailUrl: ImagesSVL.icDemoCoca,
        company: 'Tập đoàn Giải khát CocaCola',
        address: '115 Phan Bội Châu, An Thạnh, Hồng Ngự',
        salary: 'Thảo thuận',
        typeWork: 'Toàn thời gian',
        thoihan: '30/11/2021',
        view: '957',
        typeCompany: 'Loại hình: Doanh nghiệp, công ty \n \n Số lao động cần tuyển: 10 nam/ nữ \n \n Ngành nghề: Chuyên viên \n \n Chức danh: Nhân viên/ công nhân \n \n Loại hình lao động: Người lao động',
        Mota: `JOB SUMMARY\nResponsible for attaining volume targets in identified and assigned key channels through excellent execution of channel development programs (promotions, exclusivity, etc.)\n\nRESPONSIBILITY\n - Lead the development of the trade category plan for assigned channels:\n - Develop customer & shopper insights for assigned channels. Translate insights into business building opportunities within specific customers/ channels;\n - Build account/ channel specific trade plans to align with total trade category plan to deliver category/ brand objectives;\n - Identify trade spend opportunities and allocate funds for each sector while analyzing risks;\n - Match brand objectives with customer/ market needs. Work with field sales team to ensure excellence in in-store activation;`,
        yeucau: `- Bachelor's degree or Master's degree\n - Having 3-4 years’ experience in the Trade Marketing and Brand Activation areas of FMCG Industry\n - Good English ability in both writing and speaking\n - Strong analytical, communication, innovation, problem solving and decision-making skills\n - Ability to work under pressure in a dynamic environment;\n - Ability to influence/ motivate and work with teams\n - Creative & innovative`,
        isSave: false,
        isApply: false,
        appliedDate: '10:38 25/12/2021',
        status: 2,
        dateInterview: '08:30 15/1/2022',
        dataUser: {
            name: 'Đào Xuân Thứ',
            SDT: '0977 554 889',
            address: '115 Phan Bội Châu, An Thạnh, Hồng Ngự, Đồng Tháp',
            submitt: false
        }
    },
    {
        id: 7,
        title: 'Developer (.Net, Asp.net, AngularJS)',
        thumbnailUrl: ImagesSVL.icDemoVus,
        company: 'Công ty Cổ phần Công nghệ Vus',
        address: '45 Trương Định, An Thạnh, Hồng Ngự',
        salary: '500$ - 2500$',
        typeWork: 'Bán thời gian',
        thoihan: '30/11/2021',
        view: '453',
        typeCompany: 'Loại hình: Doanh nghiệp, công ty \n \n Số lao động cần tuyển: 10 nam/ nữ \n \n Ngành nghề: Chuyên viên \n \n Chức danh: Nhân viên/ công nhân \n \n Loại hình lao động: Người lao động',
        Mota: `Hỗ trợ phần mềm\n\n- Xử lý sự cố, khắc phục lỗi phần mềm khi có yêu cầu.\n - Xây dựng thêm chức năng, report cho phần mềm dựa trên tài liệu phân tích nghiệp vụ.\n\n Xây dựng và phát triển phần mềm cho hệ thống.\n - Kinh nghiệm đọc và xử lí, tổ chức code tốt, nắm bắt yêu cầu nghiệp vụ nhanh.\n - Tham gia xây dựng lại phần mềm lõi, xây dựng report, vận hành phần mềm mới trên nền công nghệ mới.`,
        yeucau: `Trình độ: Đại học, chuyên ngành Công nghệ thông tin, công nghệ phần mềm\n\nĐộ tuổi: 24-28\n Kinh nghiệm: ít nhất 2 năm\n Thái độ: tích cực, ham học hỏi, chịu được áp lực\n Ngoại ngữ: Trung cấp (# level B)\n\nSkills and Qualifications/ Kỹ năng Nghiệp vụ:\n - Có khả năng thuyết trình, giao tiếp tốt, có khả năng làm việc nhóm`,
        isSave: true,
        isApply: false,
        appliedDate: '10:38 25/12/2021',
        status: 1,
        dateInterview: '08:30 15/1/2022',
        dataUser: {
            name: 'Trần Thị Bích',
            SDT: '0997 054 666',
            address: '45 Trương Định, An Thạnh, Hồng Ngự, Đồng Tháp',
            submitt: false
        }
    }
];