export const GETLIST_MESSAGE = 'GETLIST_MESSAGE';
export const GETLIST_ROOM = 'GETLIST_ROOM';
export const SENDMESSAGE = 'SENDMESSAGE';
export const LOADDING = 'LOADDING';
export const SUSSCESS = 'SUSSCESS';
export const SET_MESSAGE = 'SET_MESSAGE';
export const SET_MESSAGE_NEW = 'SET_MESSAGE_NEW';
export const CHANGE_TYPE_MESSAGE = 'CHANGE_TYPE_MESSAGE';
export const CHANGE_ID_MESSAGE = 'CHANGE_ID_MESSAGE';


export const GET_API_INFOCHAT = 'GET_INFOCHAT';
export const SET_INFOCHAT = 'SET_INFOCHAT';
export const SET_LISTGROUPCHAT = 'SET_LISTGROUPCHAT';
export const REMOVEMESSAGE = 'REMOVEMESSAGE';
export const REMOVEMESSAGE_SENKEY = 'REMOVEMESSAGE_SENKEY';

export const DELETEALLMESSAGE = 'DELETEALLMESSAGE';
export const SEND_LISTFILE = 'SEND_LISTFILE';
export const UPDATE_MESSAGEFILE = 'UPDATE_MESSAGEFILE';
export const LIST_SENDFILE = 'LIST_SENDFILE';
export const SETEMPTYMESSAGE = 'SETEMPTYMESSAGE';
export const SETISCHAT = 'SETISCHAT';
export const SETICONCHAT = 'SETICONCHAT';
export const LOGOUTCHAT = 'LOGOUTCHAT';

export const STATUS_CONNECT = 'STATUS_CONNECT';
export const STATUS_CONNECT_RUN = 'STATUS_CONNECT_RUN';
export const STATUS_NOTIFY = 'STATUS_NOTIFY';

export const ASYNCDDATA = 'ASYNCDDATA';


//group
export const CHANGE_CURRENT_GROUP = 'CHANGE_CURRENT_GROUP';
export const SETLIST_MESSAGE_OFGROUP = 'SETLIST_MESSAGE_OFGROUP';
export const SETITEM_MESSAGE_OFGROUP = 'SETITEM_MESSAGE_OFGROUP';
export const CHANGETYPE_ITEM_MESSAGE_OFGROUP = 'CHANGETYPE_ITEM_MESSAGE_OFGROUP';
export const CHANGID_ITEM = 'CHANGID_ITEM';
export const DELETE_ALL_MESSAGE_OFGROUP = 'DELETE_ALL_MESSAGE_OFGROUP';
export const DELETE_ITEM_MESSAGE_OFGROUP_BYSENDKEY = 'DELETE_ITEM_MESSAGE_OFGROUP_BYSENDKEY';
export const DELETE_ITEM_MESSAGE_OFGROUP_BYIDCHAT = 'DELETE_ITEM_MESSAGE_OFGROUP_BYIDCHAT';
export const CHANGE_ITEM_ID = 'CHANGE_ITEM_ID';
export const CHECK_DATA = 'CHECK_DATA';
export const ADDFILE_SENDOFGROUP = 'ADDFILE_SENDOFGROUP';
export const UPDATEFILE_SENDOFGROUP = 'UPDATEFILE_SENDOFGROUP';

export const SETDATA_SENDFILE = 'SETDATA_SENDFILE';
export const UPDATEDATA_SENDFILE = 'UPDATEDATA_SENDFILE';
export const REMOVEDATA_SENDFILE = 'REMOVEDATA_SENDFILE';

export const SET_ITEM_FILE_LOAD = "SET_ITEM_FILE_LOAD";
export const CHANGE_NEW_MESSAGE_OF_GROUP='CHANGE_NEW_MESSAGE_OF_GROUP';





//list group
export const SETLIST_GROUPCHAT = 'SETLIST_GROUPCHAT';
export const SETINFO_CURRENTGROUP = 'SETINFO_CURRENTGROUP';

//
export const DATA_SYNCHRONIZATION = 'DATA_SYNCHRONIZATION';