//new

export const SAVE_INFO = 'SAVE_INFO';
export const SETLANGUAGE = 'setlanguage';
export const GETLIST_LINHVUC = 'GETLIST_LINHVUC';
export const GETLIST_CHUYENMUC = 'GETLIST_CHUYENMUC';
export const GETLIST_MUCDOALL = 'GETLIST_MUCDOALL';
export const GETLIST_NGUONPHANANH = 'GETLIST_NGUONPHANANH';
export const GETLIST_DONVIAPP = 'GETLIST_DONVIAPP';
export const GETLIST_MUCDOALL_NB = 'GETLIST_MUCDOALL_NB';
export const GETLIST_DONVIAPP_NB = 'GETLIST_DONVIAPP_NB';
export const STATUS_CONNECT = 'STATUS_CONNECT';
export const STATUS_CONNECT_RUN = 'STATUS_CONNECT_RUN';
export const STATUS_NOTIFY = 'STATUS_NOTIFY';
export const ASYNCDDATA = 'ASYNCDDATA';
export const RESET_STORE = 'RESET_STORE';

export const TypeActionAuth = {
    SET_USER_APP: 'SET_USER_APP',
    SET_TOKEN_APP: 'SET_TOKEN_APP',
    SET_CONFIG_APP: 'SET_CONFIG_APP',
    LOGOUT_APP: 'LOGOUT_APP',
    CHECK_LIENKET: 'CHECK_LIENKET',
    SET_DATA_LIENKET: 'SET_DATA_LIENKET',
    CHECK_CONNECT_CHAT: 'CHECK_CONNECT_CHAT',
    SET_RULE_APPCANBO: 'SET_RULE_APPCANBO',
    SET_TYPE_USERCHAT: 'SET_TYPE_USERCHAT',
    SET_MENU_DICHBENH: 'SET_MENU_DICHBENH',
    SET_LIST_USER_APP: 'SET_LIST_USER_APP',
    SET_TOKEN_LIST_APP: 'SET_TOKEN_LIST_APP',
    CHECK_LOGIN_LIST_APP_SPECIAL: 'CHECK_LOGIN_LIST_APP_SPECIAL',
    SET_GLOBAL_STORE_APP: 'SET_GLOBAL_STORE_APP',
}

export const TypeThemeHeader = {
    SET_COLOR_LINEAR: 'SET_COLOR_LINEAR',
    SET_BACKGROUND_HOME: 'SET_BACKGROUND_HOME',
    SET_BLUR_BACKGROUND: 'SET_BLUR_BACKGROUND',
    SET_BACKGROUND_ONLINE: 'SET_BACKGROUND_ONLINE',
    SET_BACKGROUND_FULL: 'SET_BACKGROUND_FULL',
    SET_IMAGE_HEADER_MENU: 'SET_IMAGE_HEADER_MENU',
    SET_TYPE_MENU: 'SET_TYPE_MENU',
    SET_TRANSPAENT_AREA_MENU: 'SET_TRANSPAENT_AREA_MENU',
    SHOW_MODAL_NOTI: 'SHOW_MODAL_NOTI',
    SET_LANDSCAPE: 'SET_LANDSCAPE',
    SET_IMGHOME: 'SET_IMGHOME'
}

// listObjectDH: [],
// listObjectRuleDH: [],
// listObjectSpecialDH: [],
// listObjectRuleCD: objectMenu.MenuCongDong,
export const TypeMenu = {
    SET_MENU_CANBO: 'SET_MENU_CANBO',
    SET_MENU_CONGDONG: 'SET_MENU_CONGDONG',
    SET_OBJECT_MENU: 'SET_OBJECT_MENU',
    SET_SHOWAPP_G: 'SET_SHOWAPP_G',
    LOAD_MENU: 'LOAD_MENU',

    SET_LIST_OBJECTDH: 'SET_LIST_OBJECTDH',
    SET_LIST_OBJECT_RULE_DH: 'SET_LIST_OBJECT_RULE_DH',
    SET_LIST_OBJECT_SPECIAL_DH: 'SET_LIST_OBJECT_SPECIAL_DH',

}
export const TypeCommon = {
    SET_DESIGN: 'SET_DESIGN_APP',
    SET_CONFIG: 'SET_CONFIG_APP',
    SET_CAMERA_ANNINH: 'SET_CAMERA_ANNINH',
    SET_KEY_CAMERA: 'SET_KEY_CAMERA',
    SET_LISTCAM: 'SET_LISTCAM',
    SET_CHECK_LIST_CAM: 'SET_CHECK_LIST_CAM',

}

export const TypeDataHCM = {
    SET_LIST_PROVINCE: 'SET_LIST_PROVINCE',
    GET_LIST_PROVINCE: 'GET_LIST_PROVINCE',
    SAVE_CHOTKIEMDICH: 'SAVE_CHOTKIEMDICH',
    SAVE_LISTCHOT: 'SAVE_LISTCHOT',
    SAVE_LISTPHUTHUOC: 'SAVE_LISTPHUTHUOC',
    SAVE_DIEMTIEM: 'SAVE_DIEMTIEM',
    SAVE_TINHHINHSUCKHOE: 'SAVE_TINHHINHSUCKHOE',
    SAVE_CHOTCHO: 'SAVE_CHOTCHO',
}

export const TypeNotification = {
    //Cộng đồng
    SET_REFRESHING: 'SET_REFRESHING',
    GET_THONGBAO_CONGDONG: 'GET_THONGBAO_CONGDONG',
    LOADMORE_THONGBAO_CONGDONG: 'LOADMORE_THONGBAO_CONGDONG',
    DELETE_THONGBAO_CONGDONG: 'DELETE_THONGBAO_CONGDONG',
    DELETE_ALL_THONGBAO_CONGDONG: 'DELETE_ALL_THONGBAO_CONGDONG', // chưa xử lý
    SEEN_THONGBAO_CONGDONG: 'SEEN_THONGBAO_CONGDONG',

    //Điều hành
    SET_REFRESHING_CANBO: 'SET_REFRESHING_CANBO',
    GET_THONGBAO_CANBO: 'GET_THONGBAO_CANBO',

    //Chuyên mục
    SET_REFRESHING_CM: 'SET_REFRESHING_CM',
    GET_CHUYENMUC: 'GET_CHUYENMUC',
    LOADMORE_CHUYENMUC: 'LOADMORE_CHUYENMUC',
    RECEIVE_NOTIFYCATION: 'RECEIVE_NOTIFYCATION',
    UNRECEIVE_NOTIFYCATION: 'UNRECEIVE_NOTIFYCATION',


    //Dịch vụ công
    SET_LISTNOTI_DVC: 'SET_LISTNOTI_DVC',
    LOADMORE_NOTI_DVC: 'LOADMORE_NOTI_DVC',
    SET_REFRESHING_DVC: 'SET_REFRESHING_DVC',

    GET_ALL_THONGBAO_CD: 'GET_ALL_THONGBAO_CD'
}


//Sàn Việc Làm - SVL
export const TypeDataSVL = {
    SET_DS_TUYENDUNG: 'SET_DS_TUYENDUNG',
    SET_DS_LSTIMKIEM: 'SET_DS_LSTIMKIEM',
    SET_CV: 'SET_CV',
    SET_CV_Default: 'SET_CV_Default',
    SET_CV_Item: 'SET_CV_Item',
    SET_TinTuyenDung: 'SET_TinTuyenDung',
    SET_DATA_FILTER: 'SET_DATA_FILTER',

    //Danh sách tin tuyển dụng + bộ lọc
    SET_DATA_RECRUITMENT: 'SET_DATA_RECRUITMENT',
    SET_REFRESHING_RECRUITMENT: 'SET_REFRESHING_RECRUITMENT',
    SET_PAGE_RECRUITMENT: 'SET_PAGE_RECRUITMENT',
    UNLIKE_RECRUITMENT: 'UNLIKE_RECRUITMENT',
    LIKE_RECRUITMENT: 'LIKE_RECRUITMENT',
    SET_DATA_TINTuyenDung: ' SET_DATA_TINTuyenDung',

    //Danh sách tin đã lưu
    SET_DATA_RECRUITMENTSAVED: 'SET_DATA_RECRUITMENTSAVED',
    SET_REFRESHING_RECRUITMENTSAVED: 'SET_REFRESHING_RECRUITMENTSAVED',
    SET_PAGE_RECRUITMENTSAVED: 'SET_PAGE_RECRUITMENTSAVED',
    UNLIKE_RECRUITMENTSAVED: 'UNLIKE_RECRUITMENTSAVED',

    //Danh sách tin CV giành cho Doanh nghiệp
    SET_DATA_PROFILE_ENTERPRISE: 'SET_DATA_PROFILE_ENTERPRISE',
    SET_REFRESHING_PROFILE_ENTERPRISE: 'SET_REFRESHING_PROFILE_ENTERPRISE',
    SET_PAGE_PROFILE_ENTERPRISE: 'SET_PAGE_PROFILE_ENTERPRISE',
    UNLIKE_PROFILE_ENTERPRISE: 'UNLIKE_PROFILE_ENTERPRISE',
    LIKE_PROFILE_ENTERPRISE: 'LIKE_PROFILE_ENTERPRISE',

    //Lịch sử ứng tuyển cá nhân ( người lao động)
    SET_DATA_APPLIED: 'SET_DATA_APPLIED',
    SET_REFRESHING_APPLIED: 'SET_REFRESHING_APPLIED',
    LIKE_UNLIKE_APPLIED: 'LIKE_UNLIKE_APPLIED',

    // Danh sách CV dành cho user
    SET_DATA_CV_USER: 'SET_DATA_CV_USER',
    SET_REFRESHING_CV_USER: 'SET_REFRESHING_CV_USER',
    DELETE_CV_USER: 'DELETE_CV_USER', // map lại dữ liệu
    CHECKED_DELETE_CV_USER: 'CHECKED_DELETE_CV_USER',
    CHANGE_ISPUBLIC_CV_USER: 'CHANGE_ISPUBLIC_CV_USER', // đổi trạng thái hồ sơ

    //Danh sách hồ sơ CV đã lưu
    SET_DATA_CV_SAVED: 'SET_DATA_CV_SAVED',
    SET_REFRESHING_CV_SAVED: 'SET_REFRESHING_CV_SAVED',
    SET_PAGE_CV_SAVED: 'SET_PAGE_CV_SAVED',
    UNLIKE_CV_SAVED: 'UNLIKE_CV_SAVED',
    // Danh sách tin tuyển dụng của doanh nghiệp (chọn Tin trong phần ứng tuyển)
    SET_DATA_RECRUITMENT_POST: 'SET_DATA_RECRUITMENT_POST',
    SET_REFRESHING_RECRUITMENT_POST: 'SET_REFRESHING_RECRUITMENT_POST',
    DELETE_RECRUITMENT_POST: 'DELETE_RECRUITMENT_POST', // map lại dữ liệu
    CHECKED_RECRUITMENT_POST: 'CHECKED_RECRUITMENT_POST',
    SELECT_RECRUITMENT_POST: 'SELECT_RECRUITMENT_POST',
    //Lịch sử tuyển dụng  (Doanh nghiệp) -
    SET_DATA_PROFILEAPPLIED: 'SET_DATA_PROFILEAPPLIED',
    SET_REFRESHING_PROFILEAPPLIED: 'SET_REFRESHING_PROFILEAPPLIED',
    LIKE_UNLIKE_PROFILEAPPLIED: 'LIKE_UNLIKE_PROFILEAPPLIED',
    // Danh sách bài đăng - doanh nghiệp (đăng tin)
    SET_DATA_EMPLOYMENT: 'SET_DATA_EMPLOYMENT',
    SET_REFRESHING_EMPLOYMENT: 'SET_REFRESHING_EMPLOYMENT',
    SET_PAGE_EMPLOYMENT: 'SET_PAGE_EMPLOYMENT',
    DELETE_EMPLOYMENT: 'DELETE_EMPLOYMENT', // map lại dữ liệu
    CHECKED_DELETE_EMPLOYMENT: 'CHECKED_DELETE_EMPLOYMENT',
    CHANGE_HIDESHOW_EMPLOYMENT: 'CHANGE_HIDESHOW_EMPLOYMENT', // ẩn hiện bài đăng
    //Danh sách thông báo - người lao động
    SET_DATA_MAILBOX: 'SET_DATA_MAILBOX',
    SET_REFRESHING_MAILBOX: 'SET_REFRESHING_MAILBOX',
    SET_PAGE_MAILBOX: 'SET_PAGE_MAILBOX',
    SET_COUNT_MAILBOX: 'SET_COUNT_MAILBOX',
    READ_MAILBOX: 'READ_MAILBOX',
    READ_ALL_MAILBOX: 'READ_ALL_MAILBOX',
    //Danh sách thông báo - doanh nghiệp
    SET_DATA_MAILBOX_ENTERPRISE: 'SET_DATA_MAILBOX_ENTERPRISE',
    SET_REFRESHING_MAILBOX_ENTERPRISE: 'SET_REFRESHING_MAILBOX_ENTERPRISE',
    SET_PAGE_MAILBOX_ENTERPRISE: 'SET_PAGE_MAILBOX_ENTERPRISE',
    SET_COUNT_MAILBOX_ENTERPRISE: 'SET_COUNT_MAILBOX_ENTERPRISE',
    READ_MAILBOX_ENTERPRISE: 'READ_MAILBOX_ENTERPRISE',
    READ_ALL_MAILBOX_ENTERPRISE: 'READ_ALL_MAILBOX_ENTERPRISE',
    //Danh sách CV user public
    SET_DATA_CV_USER_PUBLIC: 'SET_DATA_CV_USER_PUBLIC',

}

export const TypeWidget = {
    SET_DATA_TAO_SUA_TINRAOVAT: 'SET_DATA_TAO_SUA_TINRAOVAT',

    //TIN RAO VAT CA NHAN
    SET_DATA_RAOVATCANHAN: 'SET_DATA_RAOVATCANHAN',
    SET_REFRESHING_RAOVATCANHAN: 'SET_REFRESHING_RAOVATCANHAN',
    SET_PAGE_RAOVATCANHAN: 'SET_PAGE_RAOVATCANHAN',
    DELETE_TINRAOVAT_CANHAN: 'DELETE_TINRAOVAT_CANHAN',


    //TIN RAO VAT
    SET_DATA_TINRAOVAT: 'SET_DATA_TINRAOVAT',
    SET_REFRESHING_TINRAOVAT: 'SET_REFRESHING_TINRAOVAT',
    SET_PAGE_TINRAOVAT: 'SET_PAGE_TINRAOVAT',
    SET_LIKE_UNLIKE_TINRAOVAT: 'SET_LIKE_UNLIKE_TINRAOVAT',

    //TIN RAO VAT CA NHAN
    SET_DATA_TINRAOVAT_DALUU: 'SET_DATA_TINRAOVAT_DALUU',
    SET_REFRESHING_TINRAOVAT_DALUU: 'SET_REFRESHING_TINRAOVAT_DALUU',
    SET_PAGE_TINRAOVAT_DALUU: 'SET_PAGE_TINRAOVAT_DALUU',
    SET_LIKE_UNLIKE_TINRAOVAT_DALUU: 'SET_LIKE_UNLIKE_TINRAOVAT_DALUU',
    SET_TRANGTHAITIN_ITEM: 'SET_TRANGTHAITIN_ITEM',

    SET_TRANGTHAIHIENTHI_ITEM: 'SET_TRANGTHAIENTHI_ITEM',

    //Tim kiem gan day
    SAVE_KEY_TIMKIEM: 'SAVE_KEY_TIMKIEM',
    DELETE_KEY_TIMKIEM: 'DELETE_KEY_TIMKIEM',

    SET_DATA_TAO_SUA_TINTHUENHA: 'SET_DATA_TAO_SUA_TINTHUENHA',
    //Tin thue nha ca nhan
    SET_DATA_TINTHUENHACANHAN: 'SET_DATA_TINTHUENHACANHAN',
    SET_REFRESHING_TINTHUENHACANHAN: 'SET_REFRESHING_TINTHUENHACANHAN',
    SET_PAGE_TINTHUENHACANHAN: 'SET_PAGE_TINTHUENHACANHAN',
    DELETE_TINTHUENHACANHAN: 'DELETE_TINTHUENHACANHAN',
    SET_TRANGTHAITINTHUENHA: 'SET_TRANGTHAITINTHUENHA',

    //TIN RAO VAT
    SET_DATA_TINTHUENHA: 'SET_DATA_TINTHUENHA',
    SET_REFRESHING_TINTHUENHA: 'SET_REFRESHING_TINTHUENHA',
    SET_PAGE_TINTHUENHA: 'SET_PAGE_TINTHUENHA',
    SET_LIKE_UNLIKE_TINTHUENHA: 'SET_LIKE_UNLIKE_TINTHUENHA',

    //Tim kiem gan day thue nha
    SAVE_KEY_TIMKIEM_THUENHA: 'SAVE_KEY_TIMKIEM_THUENHA',
    DELETE_KEY_TIMKIEM_THUENHA: 'DELETE_KEY_TIMKIEM_THUENHA',




}










