export const ImagesHDDT = {

    icHDD: require('./img/icHDD.png'),
    icDrawer: require('./img/icDrawer.png'),
    icHoaDon: require('./img/icHoaDon.png'),
    icTabHoaDon: require('./img/icTabHoaDon.png'),
    icTabLichsu: require('./img/icTabLichsu.png'),
    icDropDown: require('./img/icDropDown.png'),
    icHoaDonActive: require('./img/icHoaDonActive.png'),
    icHoaDonBlue: require('./img/icHoaDonBlue.png'),
    icGoBack: require('./img/icGoBack.png'),
    icNuoc: require('./img/icNuoc.png'),
    icDien: require('./img/icDien.png'),
    icMang: require('./img/icMang.png'),
    icTruyenHinh: require('./img/icHDTV.png'),
    icChungCu: require('./img/icHDCC.png'),
    icHDDV: require('./img/icHDDV.png'),
    icHDK: require('./img/icHDK.png'),
    icAllHD: require('./img/icAllHD.png'),
    icHead: require('./img/icHead.png'),
    // icHead: require('./img/icHead.png'),
    icCalendar: require('./img/icCalendar.png'),
    icHeaderModal: require('./img/icHeaderModal.png'),
    icUnCheckHD: require('./img/icUnCheckHD.png'),
    icCheckHD: require('./img/icCheckHD.png'),
    icLock: require('./img/icLock.png'),
    icClose: require('./img/icClose.png'),
    icSuccess: require('./img/icSuccess.png'),
}